import './globals.scss'
import 'the-new-css-reset/css/reset.css'
import Header from '@/components/Header/Header'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.8.0/gsap.min.js"></script>
      </head>
      <body id="light">
        <Header/>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
